services:
   bourdeau_bundle_hand_evaluator.handfinder:
       class: Bourdeau\Bundle\HandEvaluatorBundle\HandEvaluator\HandFinder
       arguments: ['@bourdeau_bundle_hand_evaluator.cardvalidator']
   bourdeau_bundle_hand_evaluator.cardvalidator:
       class: Bourdeau\Bundle\HandEvaluatorBundle\HandEvaluator\CardValidator
