services:
   bourdeau_bundle_hand_evaluator.handevaluator:
       class: Bourdeau\Bundle\HandEvaluatorBundle\HandEvaluator\HandEvaluator
       arguments: ['@bourdeau_bundle_hand_evaluator.cardvalidator']
   bourdeau_bundle_hand_evaluator.cardvalidator:
       class: Bourdeau\Bundle\HandEvaluatorBundle\HandEvaluator\CardValidator
